## Лабораторная № 2. Векторное представление текстов

*Кузьмина Н.В. J4140*

###1. Скачайте данные отзывов о банковских услугах, используемые в лабораторной работе №1.

In [9]:
import pandas as pd
import numpy as np

In [53]:
# Выгрузим данные, полученные после предварительной обработки отзывов для альфа-банка:
df = pd.read_csv('alfa_bank.csv')
df

bank_href               login  \
0      /alfa-bank.html                 NaN   
1      /alfa-bank.html                 NaN   
2      /alfa-bank.html                 NaN   
3      /alfa-bank.html                 NaN   
4      /alfa-bank.html                 NaN   
...                ...                 ...   
1255  /bank/alfa-bank/              Юрий,    
1256  /bank/alfa-bank/             Павел,    
1257  /bank/alfa-bank/  Анна Мордовченко,    
1258  /bank/alfa-bank/            оксана,    
1259  /bank/alfa-bank/           Валерия,    

                                                 review   bank_name  \
0     История номер раз\nКредитная карта Aeroflot Go...  альфа-банк   
1     Отличный банк Хорошие депозиты, высокие процен...  альфа-банк   
2     Только что с жену ограбили во время съёма дене...  альфа-банк   
3     Заполнила заявку на получение дебетовой карты ...  альфа-банк   
4     О сервисе Альфа-клик думаю плохо. Очень плохо....  альфа-банк   
...                                                 ...         ...   
1255  Прямо приятно было деньги отдавать :-) Нет, ну...  альфа-банк   
1256                           Хороший банкХороший банк  альфа-банк   
1257  Общение с клиентами дистанционноОформила креди...  альфа-банк   
1258  Нарушены все сроки рассмотрения заявок на ипот...  альфа-банк   
1259  Взяла кредит у Альфа-банк в апреле 2012 на 5 л...  альфа-банк   

                       site           date  \
0     http://bankireview.ru            NaN   
1     http://bankireview.ru            NaN   
2     http://bankireview.ru            NaN   
3     http://bankireview.ru            NaN   
4     http://bankireview.ru            NaN   
...                     ...            ...   
1255  https://www.sravni.ru   19 окт, 2015   
1256  https://www.sravni.ru   20 окт, 2015   
1257  https://www.sravni.ru  30 сент, 2018   
1258  https://www.sravni.ru   03 окт, 2018   
1259  https://www.sravni.ru   22 авг, 2015   

                            message_href score status user_href  \
0                                    NaN   NaN    NaN       NaN   
1                                    NaN   NaN    NaN       NaN   
2                                    NaN   NaN    NaN       NaN   
3                                    NaN   NaN    NaN       NaN   
4                                    NaN   NaN    NaN       NaN   
...                                  ...   ...    ...       ...   
1255  /bank/alfa-bank/otzyv/178722/?page     5    NaN       NaN   
1256      /bank/alfa-bank/otzyv/83/?page     2    NaN       NaN   
1257  /bank/alfa-bank/otzyv/299285/?page     3    NaN       NaN   
1258  /bank/alfa-bank/otzyv/299519/?page     1    NaN       NaN   
1259  /bank/alfa-bank/otzyv/170625/?page     1    NaN       NaN   

                                      preprocessed_text  
0     история номер кредитный карта aeroflot gold об...  
1     отличный банк хороший депозит высокий процент ...  
2     жена ограбить время съём деньга банкомат допол...  
3     заполнить заявка получение дебетовый карта nex...  
4     сервис альфа-клик думать плохо очень плохо поя...  
...                                                 ...  
1255  прямо приятно деньга отдавать правда случиться...  
1256                           хороший банкхороший банк  
1257  общение клиент дистанционнооформить кредит тел...  
1258  нарушить срок рассмотрение заявка ипотека пода...  
1259  взять кредит альфа-банк апрель 2012 5 год кром...  

[1260 rows x 11 columns]

In [54]:
# Преобразуем значения "Без оценки" в NaN
df['score'] = df['score'].replace('Без оценки', np.nan)

# Преобразуем значения в столбце 'score' в числовой тип данных
df['score'] = pd.to_numeric(df['score'], errors='coerce')

# Вычисляем среднее значение столбца 'score'
mean_score = df['score'].mean()

# Заменяем NaN значения на среднее значение столбца 'score'
df['score'] = df['score'].fillna(mean_score)

In [55]:
df.shape

(1260, 11)

### 2. Постройте векторные представления отзывов с использованием подходов BoW и TF-IDF c разными параметрами (использование n-gramm, различные пороги по отсечению частотных слов), а также с использованием предобучененных векторов word2vec.

In [56]:
# Мешок слов (Bag of Words, BoW)
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
# векторизуем сразу весь корпус
vectorizer = CountVectorizer()
X_BoW = vectorizer.fit_transform(df['preprocessed_text']).toarray()

In [58]:
np.save('BoW', X_BoW)

In [59]:
X_BoW.shape

(1260, 12613)

In [60]:
X_BoW

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [61]:
df_BOW = pd.DataFrame(X_BoW)

In [62]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [63]:
vectorizer = TfidfVectorizer()
X_TF_IDF = vectorizer.fit_transform(df['preprocessed_text']).toarray()

In [64]:
np.save('TF_IDF', X_TF_IDF)

In [65]:
X_TF_IDF.shape

(1260, 12613)

In [66]:
X_TF_IDF

array([[0.        , 0.03882388, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0558277 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [67]:
df_TF_IDF = pd.DataFrame(X_TF_IDF)

In [68]:
# Word2Vec
import gensim.downloader as api
import time

In [35]:
# загружаем предобученную модель
wv = api.load('word2vec-ruscorpora-300')

[==================================================] 100.0% 198.8/198.8MB downloaded


In [69]:
# создание списка слов без частей речи
vocab = []
for w in list(wv.index_to_key):
  vocab.append(w.split('_')[0])

In [72]:
# Список векторов текстов для всего корпуса
vectors_corpus = []

# Для отслеживания прогресса выполнения
count = 0

# Время начала выполнения цикла. Для подсчета времени выполнения
start = time.time()

for x in range (1260):

    # Каждые 100 текстов выводится информация об количестве обработанных текстов
    if count % 100 == 0:
        print(count)

    # Выбор текущей строки из датафрейма
    preprocessing_text_list = df.loc[x]['preprocessed_text'].split()

    # Список векторов текущего текста
    vectors_word = []

    for i in preprocessing_text_list:
        if i in vocab:
            vectors_word.append(wv[list(wv.index_to_key)[vocab.index(i)]])
        else:
            vectors_word.append(np.zeros(300))

    # Для отследивания прогресса
    count += 1

    # Высчитывание среднего вектора для текущего текста по векторам каждого слова
    vector_text = np.mean(vectors_word, axis = 0)

    # Добавление вектора текущего текста в список векторов корпуса
    vectors_corpus.append(vector_text)

# Время окончания выполнения цикла
end = time.time()

# Вывод времени выполнения цикла
print('It took:', end - start, 'seconds')

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
It took: 680.5797355175018 seconds


In [73]:
df_w2v = pd.DataFrame(vectors_corpus)

In [74]:
df_w2v.shape

(1260, 300)

In [75]:
df_w2v.to_csv('df_w2v.csv', index=False)

### 3. Разделите отзывы на положительные и отрицательные можно на основании значения в поле «score» (например, 1,2- негативные, 4,5-позитивные).

In [79]:
# Разделение на положительные и отрицательные отзывы

def assign_labels(scores):
    threshold = 3  # пороговое значение
    labels = []

    for score in scores:
        if score >= threshold:
            labels.append(1)  # Отзыв является положительным
        else:
            labels.append(0)  # Отзыв является отрицательным

    return labels

### 4. Классифицируйте отзывы на положительные/отрицательные с использованием разных векторных представлений. Можно использовать любую модель/модели класссификации.

**Логистическая регрессия**

In [109]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

*   BoW



In [119]:
X = df_BOW.values
Y = df['score']

In [120]:
y_labels = assign_labels(Y)

In [121]:
# разделением наш корпус данных на обучающую и тестовую выборку
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_labels,
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

In [122]:
# классификатор
clf = LogisticRegression(
        penalty = 'l2', #{‘l1’, ‘l2’, ‘elasticnet’, None}, default=’l2’
        C = 0.2, #float, default=1.0
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42,
        max_iter = 100, #int, default=100
        n_jobs = -1, #int, default=None
)
# предобученный классификатор
clf_pretrained = clf.fit(X_train, y_train)

In [123]:
# результат предсказания
y_predict = clf_pretrained.predict(X_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [124]:
# Оценка точности
print(classification_report(y_test, y_predict, digits = 4))

              precision    recall  f1-score   support

           0     0.8837    0.9179    0.9005       207
           1     0.5405    0.4444    0.4878        45

    accuracy                         0.8333       252
   macro avg     0.7121    0.6812    0.6941       252
weighted avg     0.8224    0.8333    0.8268       252



*   TF-IDF



In [125]:
X = df_TF_IDF.values
Y = df['score']

In [126]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_labels,
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

In [127]:
clf_pretrained = clf.fit(X_train, y_train)
y_predict = clf_pretrained.predict(X_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
# Оценка точности
print(classification_report(y_test, y_predict, digits = 4))

              precision    recall  f1-score   support

           0     0.8864    0.9420    0.9133       207
           1     0.6250    0.4444    0.5195        45

    accuracy                         0.8532       252
   macro avg     0.7557    0.6932    0.7164       252
weighted avg     0.8397    0.8532    0.8430       252





*   Word2Vec



In [129]:
X = df_w2v.values
Y = df['score']

In [130]:
y_labels = assign_labels(Y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_labels,
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

In [131]:
# предобученный классификатор
clf_pretrained = clf.fit(X_train, y_train)

In [132]:
# результат предсказания
y_predict = clf_pretrained.predict(X_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [133]:
# Оценка точности
print(classification_report(y_test, y_predict, digits = 4))

              precision    recall  f1-score   support

           0     0.8939    0.8551    0.8741       207
           1     0.4444    0.5333    0.4848        45

    accuracy                         0.7976       252
   macro avg     0.6692    0.6942    0.6795       252
weighted avg     0.8137    0.7976    0.8046       252



**Случайный лес**

In [110]:
from sklearn.ensemble import RandomForestClassifier

*   BoW

In [111]:
X = df_BOW.values
Y = df['score']

y_labels = assign_labels(Y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_labels,
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

clf_rf =  RandomForestClassifier(
        n_estimators = 200, #int, default=100
        criterion = 'gini', #{“gini”, “entropy”, “log_loss”}, default=”gini”
        max_depth = 200, #int, default=None
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42
)

clf_rf = clf_rf.fit(X_train, y_train)
y_predict_rf = clf_rf.predict(X_test)

print(classification_report(y_test, y_predict_rf, digits = 4))

              precision    recall  f1-score   support

           0     0.8402    0.9903    0.9091       207
           1     0.7500    0.1333    0.2264        45

    accuracy                         0.8373       252
   macro avg     0.7951    0.5618    0.5678       252
weighted avg     0.8241    0.8373    0.7872       252



*   TF-IDF

In [134]:
X = df_TF_IDF.values
Y = df['score']

y_labels = assign_labels(Y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_labels,
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

clf_rf = clf_rf.fit(X_train, y_train)
y_predict_rf = clf_rf.predict(X_test)

print(classification_report(y_test, y_predict_rf, digits = 4))

              precision    recall  f1-score   support

           0     0.8408    0.9952    0.9115       207
           1     0.8571    0.1333    0.2308        45

    accuracy                         0.8413       252
   macro avg     0.8490    0.5643    0.5711       252
weighted avg     0.8437    0.8413    0.7899       252



*   Word2Vec

In [135]:
X = df_w2v.values
Y = df['score']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_labels,
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

clf_rf = clf_rf.fit(X_train, y_train)
y_predict_rf = clf_rf.predict(X_test)

print(classification_report(y_test, y_predict_rf, digits = 4))

              precision    recall  f1-score   support

           0     0.8347    1.0000    0.9099       207
           1     1.0000    0.0889    0.1633        45

    accuracy                         0.8373       252
   macro avg     0.9173    0.5444    0.5366       252
weighted avg     0.8642    0.8373    0.7766       252



### 5. Проанализируйте точность классификации при использовании разных векторных представлений.

По полученным метрикам видно, что наибольшой точностью при использовании логистической регрессии и случайного леса обладает векторное представление TF-IDF.
Наименьшей точностью при логистической регрессии - Word2Vec.
